### ISSUE TITLE
一个Android Go机型跑过程抛出error：java.lang.Exception: Stack trace

### ISSUE THREAD

**Issue by Hanlen520** [zhangzhao4444/Maxim#21]
系统：Android Go（8.1）
MTK平台

java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1348)
	at android.graphics.Bitmap.recycle(Bitmap.java:346)
	at android.app.UiAutomation.takeScreenshot(UiAutomation.java:748)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.takeScreenshot(MonkeySourceRandomUiAutomatorMix.kt:1079)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.executeScreenshotTask(MonkeySourceRandomUiAutomatorMix.kt:1059)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.generateEvents(MonkeySourceRandomUiAutomatorMix.kt:483)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.getNextEvent(MonkeySourceRandomUiAutomatorMix.kt:76)
	at tv.panda.test.monkey.Monkey.runMonkeyCycles(Monkey.kt:1078)
	at tv.panda.test.monkey.Monkey.run(Monkey.kt:580)
	at tv.panda.test.monkey.Monkey$Companion.main(Monkey.kt:1299)
	at tv.panda.test.monkey.Monkey.main(Unknown Source:7)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1348)
	at android.graphics.Bitmap.recycle(Bitmap.java:346)
	at android.app.UiAutomation.takeScreenshot(UiAutomation.java:748)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.takeScreenshot(MonkeySourceRandomUiAutomatorMix.kt:1079)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.executeScreenshotTask(MonkeySourceRandomUiAutomatorMix.kt:1059)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.generateEvents(MonkeySourceRandomUiAutomatorMix.kt:509)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.getNextEvent(MonkeySourceRandomUiAutomatorMix.kt:76)
	at tv.panda.test.monkey.Monkey.runMonkeyCycles(Monkey.kt:1078)
	at tv.panda.test.monkey.Monkey.run(Monkey.kt:580)
	at tv.panda.test.monkey.Monkey$Companion.main(Monkey.kt:1299)
	at tv.panda.test.monkey.Monkey.main(Unknown Source:7)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1348)
	at android.graphics.Bitmap.recycle(Bitmap.java:346)
	at android.app.UiAutomation.takeScreenshot(UiAutomation.java:748)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.takeScreenshot(MonkeySourceRandomUiAutomatorMix.kt:1079)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.executeScreenshotTask(MonkeySourceRandomUiAutomatorMix.kt:1059)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.generateEvents(MonkeySourceRandomUiAutomatorMix.kt:509)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.getNextEvent(MonkeySourceRandomUiAutomatorMix.kt:76)
	at tv.panda.test.monkey.Monkey.runMonkeyCycles(Monkey.kt:1078)
	at tv.panda.test.monkey.Monkey.run(Monkey.kt:580)
	at tv.panda.test.monkey.Monkey$Companion.main(Monkey.kt:1299)
	at tv.panda.test.monkey.Monkey.main(Unknown Source:7)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)

**Comment by zhangzhao4444** [comment]
fixed
