### ISSUE TITLE
Mate30执行时报异常，麻烦看一下

### ISSUE THREAD

**Issue by pxrgod** [zhangzhao4444/Maxim#51]
[Maxim] *** ERROR // WATCHDOG: Blocked in monitor com.android.server.input.InputManagerServiceBridge on foreground thread (android.fg)
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at tv.panda.test.monkey.ape.utils.APIAdapter.j0(APIAdapter.java:121)
	at tv.panda.test.monkey.ape.utils.APIAdapter.getTasks(APIAdapter.java:175)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.getTopActivityComponentName(MonkeySourceRandomUiAutomatorMix.kt:1254)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.checkActivity(MonkeySourceRandomUiAutomatorMix.kt:1326)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.getNextEvent(MonkeySourceRandomUiAutomatorMix.kt:90)
	at tv.panda.test.monkey.Monkey.runMonkeyCycles(Monkey.kt:1173)
	at tv.panda.test.monkey.Monkey.run(Monkey.kt:623)
	at tv.panda.test.monkey.Monkey$Companion.main(Monkey.kt:1440)
	at tv.panda.test.monkey.Monkey.main(Unknown Source:2)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:532)
	at android.app.IActivityManager$Stub$Proxy.getTasks(IActivityManager.java:4989)
	... 12 more
android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:532)
	at com.android.internal.view.IInputMethodManager$Stub$Proxy.getInputMethodWindowVisibleHeight(IInputMethodManager.java:827)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.checkVirtualKeyboard(MonkeySourceRandomUiAutomatorMix.kt:1430)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.generateEvents(MonkeySourceRandomUiAutomatorMix.kt:843)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.getNextEvent(MonkeySourceRandomUiAutomatorMix.kt:92)
	at tv.panda.test.monkey.Monkey.runMonkeyCycles(Monkey.kt:1173)
	at tv.panda.test.monkey.Monkey.run(Monkey.kt:623)
	at tv.panda.test.monkey.Monkey$Companion.main(Monkey.kt:1440)
	at tv.panda.test.monkey.Monkey.main(Unknown Source:2)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
[Maxim] *** ERROR // Fail to getInputMethodWindowVisibleHeight
java.lang.RuntimeException: android.os.DeadSystemException
	at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:163)
	at android.hardware.display.DisplayManagerGlobal.getCompatibleDisplay(DisplayManagerGlobal.java:220)
	at android.hardware.display.DisplayManagerGlobal.getRealDisplay(DisplayManagerGlobal.java:253)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.generatePointerEvent(MonkeySourceRandomUiAutomatorMix.kt:451)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.generateEvents(MonkeySourceRandomUiAutomatorMix.kt:860)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.getNextEvent(MonkeySourceRandomUiAutomatorMix.kt:92)
	at tv.panda.test.monkey.Monkey.runMonkeyCycles(Monkey.kt:1173)
	at tv.panda.test.monkey.Monkey.run(Monkey.kt:623)
	at tv.panda.test.monkey.Monkey$Companion.main(Monkey.kt:1440)
	at tv.panda.test.monkey.Monkey.main(Unknown Source:2)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.os.DeadSystemException
	... 12 more
java.util.NoSuchElementException
	at java.util.LinkedList.getFirst(LinkedList.java:254)
	at tv.panda.test.monkey.MonkeySourceRandomUiAutomatorMix.getNextEvent(MonkeySourceRandomUiAutomatorMix.kt:95)
	at tv.panda.test.monkey.Monkey.runMonkeyCycles(Monkey.kt:1173)
	at tv.panda.test.monkey.Monkey.run(Monkey.kt:623)
	at tv.panda.test.monkey.Monkey$Companion.main(Monkey.kt:1440)
	at tv.panda.test.monkey.Monkey.main(Unknown Source:2)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

**Comment by zhangzhao4444** [comment]
从log上看是系统异常了，重启系统可以解决
