### ISSUE TITLE
小米手机在fast_android模式下跑的时候出现输入服务崩溃

### ISSUE THREAD

**Issue by pxrgod** [zhangzhao4444/Maxim#52]
java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
	at android.os.Parcel.createException(Parcel.java:2074)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEvent(IInputManager.java:925)
	at android.hardware.input.InputManager.injectInputEvent(InputManager.java:886)
	at com.android.commands.monkey.p.a(SourceFile:132)
	at com.android.commands.monkey.Monkey.f(SourceFile:1863)
	at com.android.commands.monkey.Monkey.a(SourceFile:1105)
	at com.android.commands.monkey.Monkey.main(SourceFile:827)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventInternal(InputManagerService.java:733)
	at com.android.server.input.InputManagerService.injectInputEvent(InputManagerService.java:707)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:422)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

**Comment by zhangzhao4444** [comment]
同学这个好像没开模拟点击，可以看下FAQ常见问题
